In [1]:
import pandas as pd

In [2]:
pm = pd.read_csv('bangkok_pm25.csv')
pm

       Year  Month  Day  UTC Hour  PM2.5  PM10_mask  Retrospective
0      2016      3    3         8   62.9          1              0
1      2016      3    3         9   62.9          1              0
2      2016      3    3        10   55.5          1              0
3      2016      3    3        11   55.5          1              0
4      2016      3    3        12   47.9          1              0
5      2016      3    3        13   43.6          1              0
6      2016      3    3        14   28.6          1              0
7      2016      3    3        15   33.6          1              0
8      2016      3    3        16   34.8          1              0
9      2016      3    3        17   31.3          1              0
10     2016      3    3        19   42.1          1              0
11     2016      3    3        20   38.6          1              0
12     2016      3    3        21   45.5          1              0
13     2016      3    3        22   49.9          1              0
14     2016      3    3        23   44.1          1              0
15     2016      3    4         0   42.1          1              0
16     2016      3    4         1   43.1          1              0
17     2016      3    4         2   44.8          1              0
18     2016      3    4         3   37.5          1              0
19     2016      3    4         4   39.6          1              0
20     2016      3    4         5   46.0          1              0
21     2016      3    4         6   43.8          1              0
22     2016      3    4         7   36.6          1              0
23     2016      3    4         8   34.2          1              0
24     2016      3    4         9   35.0          1              0
25     2016      3    4        10   30.0          1              0
26     2016      3    4        11   25.6          1              0
27     2016      3    4        12   32.1          1              0
28     2016      3    4        13   24.4          1              0
29     2016      3    4        14   32.8          1              0
...     ...    ...  ...       ...    ...        ...            ...
23308  2019      1   17        16   41.2          0              0
23309  2019      1   17        17   42.4          0              0
23310  2019      1   17        18   41.1          0              0
23311  2019      1   17        19   43.0          0              0
23312  2019      1   17        20   44.3          0              0
23313  2019      1   17        23   33.4          0              0
23314  2019      1   18         0   31.2          0              0
23315  2019      1   18         1   29.3          0              0
23316  2019      1   18         2   28.7          0              0
23317  2019      1   18         3   28.0          0              0
23318  2019      1   18         4   30.7          0              0
23319  2019      1   18         5   29.3          0              0
23320  2019      1   18         6   25.4          0              0
23321  2019      1   18         7   25.5          0              0
23322  2019      1   18         8   24.9          0              0
23323  2019      1   18         9   28.3          0              0
23324  2019      1   18        10   27.1          0              0
23325  2019      1   18        11   29.6          0              0
23326  2019      1   18        14   31.0          0              0
23327  2019      1   18        15   33.0          0              0
23328  2019      1   18        16   37.9          0              0
23329  2019      1   18        17   40.8          0              0
23330  2019      1   18        18   38.2          0              0
23331  2019      1   18        19   40.9          0              0
23332  2019      1   18        20   43.0          0              0
23333  2019      1   18        21   42.6          0              0
23334  2019      1   18        22   44.0          0              0
23335  2019      1   18        23   45.2          0              0
23336  2019      1   19         0   45.6          0              0
23337  2019      1   19         1   50.3          0              0

[23338 rows x 7 columns]

In [35]:
pm2=pm.groupby('Year').mean()
pm2

         Month        Day   UTC Hour      PM2.5  PM10_mask  Retrospective
Year
2016  7.489211  16.023172  11.526720  24.424345   0.948733            0.0
2017  6.624588  15.965906  11.451838  25.098466   0.606337            0.0
2018  6.557621  15.480670  11.470451  25.059616   0.170401            0.0
2019  1.000000   9.470309  11.427553  43.022328   0.000000            0.0

In [15]:
import matplotlib.pyplot as plt
%matplotlib inline

In [37]:
plt.plot(pm2['Year'],pm2['PM2.5'], 'r') # 'r' is the color red
plt.xlabel('Year')
plt.ylabel('PM2.5')
plt.title('pm per Year')
plt.show()

KeyError: 'Year'